name: icepick
channels:
- conda-forge
dependencies:
- python=3.7.3
- jupyterlab=1.0.1
- matplotlib=3.1.1
- pandas=0.24.2
- fiona=1.8.6
- shapely=1.6.4
- cfitsio=3.430
- geopandas=0.5.0
- h5py=2.9.0
- requests=2.22.0
- awscli=1.16.193
